/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTextField;
import model.Ples;

/**
 *
 * @author Korisnik
 */
public class UbaciSertifikatForma extends javax.swing.JFrame {

    /**
     * Creates new form UbaciVrstuPlesaForma
     */
    public UbaciSertifikatForma() {
        initComponents();
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        try {
            javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        getContentPane().setBackground(new java.awt.Color(230, 230, 255));

        Color fieldColor = new java.awt.Color(245, 245, 255);
        Color labelColor = new java.awt.Color(120, 80, 255);
        Color buttonColor = new java.awt.Color(180, 150, 255);

        Font labelFont = new java.awt.Font("Segoe UI", Font.PLAIN, 14);
        Font buttonFont = new java.awt.Font("Segoe UI", Font.BOLD, 13);

        jComboBoxPles.setBackground(fieldColor);

        jTextFieldOrganizacija.setBackground(fieldColor);

        jLabel1.setFont(labelFont);
        jLabel1.setForeground(labelColor);

        jLabel2.setFont(labelFont);
        jLabel2.setForeground(labelColor);

        jButtonDodaj.setFont(buttonFont);
        jButtonDodaj.setBackground(buttonColor);
        jButtonDodaj.setForeground(Color.WHITE);

        jButtonVratiSeNaGf.setFont(buttonFont);
        jButtonVratiSeNaGf.setBackground(buttonColor);
        jButtonVratiSeNaGf.setForeground(Color.WHITE);

        jButtonDodaj.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        jButtonVratiSeNaGf.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldOrganizacija = new javax.swing.JTextField();
        jComboBoxPles = new javax.swing.JComboBox<>();
        jButtonDodaj = new javax.swing.JButton();
        jButtonVratiSeNaGf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ples");

        jLabel2.setText("Organizacija koja je izdala sertifikat");

        jComboBoxPles.setModel(new DefaultComboBoxModel (Ples.values()));

        jButtonDodaj.setText("Dodaj sertifikat");

        jButtonVratiSeNaGf.setText("Vrati se na glavnu formu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldOrganizacija, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addComponent(jComboBoxPles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonVratiSeNaGf)
                            .addComponent(jButtonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jComboBoxPles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jTextFieldOrganizacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVratiSeNaGf)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getjTextFieldOrganizacija() {
        return jTextFieldOrganizacija;
    }

    public JComboBox<String> getjComboBoxPles() {
        return jComboBoxPles;
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonVratiSeNaGf;
    private javax.swing.JComboBox<String> jComboBoxPles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldOrganizacija;
    // End of variables declaration//GEN-END:variables

    public void dodajAddActionListener(ActionListener actionListener) {
        jButtonDodaj.addActionListener(actionListener);
    }

    public void vratiNaGFAddActionListener(ActionListener actionListener) {
        jButtonVratiSeNaGf.addActionListener(actionListener);
    }
}
